{ pkgs, lib, ... }:
lib.mkIf pkgs.stdenv.isLinux {
  # DGOP color configuration
  # Colors are automatically generated by matugen when enableDynamicTheming is enabled
  # in DankMaterialShell configuration
  xdg.configFile."dgop/colors.json".text = ''
    {
      "ui": {
        "border_primary": "#ccbeff",
        "border_secondary": "#cac3dc",
        "header_background": "#ccbeff",
        "header_text": "#33275e",
        "footer_background": "#141318",
        "footer_text": "#cac4cf",
        "text_primary": "#e6e1e9",
        "text_secondary": "#cac4cf",
        "text_accent": "#ccbeff",
        "selection_background": "#ccbeff",
        "selection_text": "#33275e"
      },
      "charts": {
        "network_download": "#ccbeff",
        "network_upload": "#4a3e76",
        "network_line": "#cac3dc",
        "cpu_core_low": "#4a3e76",
        "cpu_core_medium": "#ccbeff",
        "cpu_core_high": "#eeb8ca",
        "disk_read": "#ccbeff",
        "disk_write": "#4a3e76"
      },
      "progress_bars": {
        "memory_low": "#4a3e76",
        "memory_medium": "#ccbeff",
        "memory_high": "#eeb8ca",
        "disk_low": "#4a3e76",
        "disk_medium": "#ccbeff",
        "disk_high": "#eeb8ca",
        "cpu_low": "#4a3e76",
        "cpu_medium": "#ccbeff",
        "cpu_high": "#eeb8ca",
        "progress_background": "#201f24"
      },
      "temperature": {
        "cold": "#4a3e76",
        "warm": "#ccbeff",
        "hot": "#eeb8ca",
        "danger": "#ffb4ab"
      },
      "status": {
        "success": "#22C55E",
        "warning": "#F59E0B",
        "error": "#ffb4ab",
        "info": "#ccbeff"
      }
    }
  '';
}
